my second commit

diff --git a/.github/workflows/01.building-blocks.yaml b/.github/workflows/01.building-blocks.yaml
--- a/.github/workflows/01.building-blocks.yaml
+++ b/.github/workflows/01.building-blocks.yaml
@@ -1,18 +1,22 @@
 name: 01-Building Blocks
 on:
     workflow_dispatch
+
 jobs:
     echo-hello:
         runs-on: ubutntu-latest
         steps:
           - name: Say Hello
-            run: "Hello, World"
+            run: echo "Hello, World"
 
     echo-goodbye:
         runs-on: ubuntu-latest
         steps:
             - name: Failed Step
-              run: "i will fail"
+              run: | 
+                echo "i will fail"
+                exit 1                
+
 
             - name: Say goodbye
-              run: "Goodbye"
+              run: echo "Goodbye"
